version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY-}meter-readings
    build:
      context: .
      dockerfile: /MeterReadings.API/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - SQL_CONNECTIONSTRING=Server=sqldb,1433;Database=MeterReadings;user=sa;password=ENSEKTest2022;MultipleActiveResultSets=true
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "ENSEKTest2022"
        ACCEPT_EULA: "Y"
    ports:
        - 14333:1433